#!/bin/bash

echo "=== Google Workspace API Setup ==="
echo ""
echo "To run the automation, you need to:"
echo ""
echo "1. Go to: https://console.cloud.google.com"
echo "2. Create a new project or select existing"
echo "3. Enable these APIs:"
echo "   - Admin SDK API"
echo "   - Groups Settings API"
echo "   - Gmail API"
echo "   - Drive API"
echo ""
echo "4. Create credentials:"
echo "   - Go to APIs & Services > Credentials"
echo "   - Create OAuth 2.0 Client ID"
echo "   - Application type: Desktop app"
echo "   - Download as credentials.json"
echo ""
echo "5. Place credentials.json in this directory"
echo ""
echo "6. Install Python dependencies:"

# Install required Python packages
pip3 install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

echo ""
echo "7. Run the automation:"
echo "   python3 automated_google_setup.py"
echo ""
echo "The script will:"
echo "✓ Create organizational units"
echo "✓ Create user accounts"
echo "✓ Create 46+ Google Groups"
echo "✓ Configure email routing"
echo "✓ Set up financial automation"
echo "✓ Add user aliases"
echo ""
echo "Ready to run when you have credentials.json!"